/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codingan;
/**
 *
 * @author acer
 */
public class Bantuan extends javax.swing.JFrame {
/*JFrame digunakan untuk mendesain model tampilan yang didalamnya dapat kita
tempatkan komponen-komponen yang dibutuhkan dalam game ini. 
Jadi class Bantuan extends javax.swing.JFrame merupakan deklarasi dari class Mulai
yang extends, jadi extends disini digunakan untuk mempermudah dalam memakai beberapa kelas
yang telah dibuat sebelumnya. Extends disini mewarisi semua fungsi dan semua fields (variabel) yang
ada di dalam kelas parent-nya yaitu javax.swing.JFrame. Jadi kelas yang diwarisi disebut sebagai kelas "child" 
sedangkan kelas yang mewarisi disebut dengan class "parent". Perlu diketahui bahwa sebuah class hanya 
diperbolehkan meng-extends satu parent saja, tidak boleh lebih.
*/
    
    /**
     * Creates new form Bantuan
     */
    public Bantuan() {
        initComponents();
        setLocationRelativeTo(null);
        /*
        Merupakan constructor Bantuan, terlihat ada pemanggilan sebuah method yaitu
        initComponets(); yang merupakan method yang di generate oleh netbeans secara
        default. setLocationRalativeTo(c:null) digunakan untuk membuat posisi Frame berada
        di tengah-tengah screen.
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Menu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. MEMASUKAN\n2. ");
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(757, 450));
        getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel9.setText("BANTUAN");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 30, 170, 45);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("1. Memasukkan username,kemudian tekan tombol mulai.\n2. Memilih Kategori.\n3. Jika memilih tebak gambar maka nanti akan muncul gambar dan beberapa pilihan dimana hanya ada satu jawaban yang benar.\n4. Jika memilih tebak teknologi maka nanti akan muncul soal dan beberapa pilihan dimana hanya ada satu jawaban yang benar.\n5. Kemudian jika telah selesai bermain maka untuk melihat score dapat menekan tombol next.\n6. Kemudian akan muncul score yang anda dapatkan.");
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 120, 610, 180);

        Menu.setBackground(new java.awt.Color(204, 102, 0));
        Menu.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 18)); // NOI18N
        Menu.setText("MENU");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        getContentPane().add(Menu);
        Menu.setBounds(60, 330, 100, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -230, 750, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        /*
        Merupakan sebuah method ActionPerformed dari Button Menu. Saat kita mengklik Button menu, button
        tersebut akan mengaktifkan ActionEvent. 
        Kelas atau inner class yang bertindak sebagai obyek pendengar action event harus mengimplementasikan 
        interface ActionListener untuk merespon adanya action event serta mendeklarasikan ulang metoda actionPerformed. 
        Method actionPerformed memerlukan kelas ActionEvent sebagai argumen parameternya.
        */
        
        /*
         Code disini digunakan untuk menampilkan frame yang kita klik. Disini digunakan 
        setVisible(true) yang merupakan fungsi yang digunakan untuk mengatur hasil agar dapat 
        ditampilkan/Aktifkan Visible Frame. Saat kita mengaturnya/menyetelnya ke setVisible(false), maka
        kita tidak dapat melihat apa pun di layar.
        
        Class anyonmous  yang berasal dari Runnable, class anonim ini menggantikan method run dari 
        interface runnable yang dapat dijalankan. Kemudian class ini dibuat instance-nya dan
        diteruskan ke method EventQueue.invokeLater, yang merupakan method statis. Method ini menambahkan
        objek ke eventQueue. Di EventQueue terdapat banyak events seperti keyboard events atau mouse events, dan lain-lain. 
        Terdapat Thread yang terus mengumpulkan data dari antrian ini. Setelah Thread mencapai class anonim, 
        maka ia akan menjalankan method run(), yang akan
        membuat instance objek class Menuawal dan mengaturnya agar terlihat.
        */
        
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuawal().setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bantuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bantuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
