/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */  
package codingan;
/**
 *
 * @author acer
 */

public class Menuawal extends javax.swing.JFrame {
    

    /**
     * Creates new form Menuawal
     */
    Sound a = new Sound();
    
    public Menuawal(){
    initComponents();
    setLocationRelativeTo(null);
//    a.loadMusic(a.fileLocation);
//    a.clip.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        MULAI = new javax.swing.JButton();
        Bantuan = new javax.swing.JButton();
        HIGHSCORE = new javax.swing.JButton();
        KELUAR = new javax.swing.JButton();
        Pengaturan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(757, 520));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ayo_tebak__1_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 90, 420, 230);

        MULAI.setBackground(new java.awt.Color(255, 204, 51));
        MULAI.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        MULAI.setText("MULAI");
        MULAI.setMaximumSize(new java.awt.Dimension(89, 21));
        MULAI.setMinimumSize(new java.awt.Dimension(89, 21));
        MULAI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MULAIActionPerformed(evt);
            }
        });
        getContentPane().add(MULAI);
        MULAI.setBounds(220, 330, 100, 40);

        Bantuan.setBackground(new java.awt.Color(255, 204, 51));
        Bantuan.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        Bantuan.setText("BANTUAN");
        Bantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BantuanActionPerformed(evt);
            }
        });
        getContentPane().add(Bantuan);
        Bantuan.setBounds(340, 330, 120, 40);

        HIGHSCORE.setBackground(new java.awt.Color(255, 204, 51));
        HIGHSCORE.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        HIGHSCORE.setText("HIGHSCORE");
        HIGHSCORE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HIGHSCOREActionPerformed(evt);
            }
        });
        getContentPane().add(HIGHSCORE);
        HIGHSCORE.setBounds(480, 330, 130, 40);

        KELUAR.setBackground(new java.awt.Color(255, 204, 51));
        KELUAR.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 12)); // NOI18N
        KELUAR.setText("KELUAR");
        KELUAR.setMaximumSize(new java.awt.Dimension(89, 21));
        KELUAR.setMinimumSize(new java.awt.Dimension(89, 21));
        KELUAR.setPreferredSize(new java.awt.Dimension(89, 21));
        KELUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KELUARActionPerformed(evt);
            }
        });
        getContentPane().add(KELUAR);
        KELUAR.setBounds(430, 400, 120, 40);

        Pengaturan.setBackground(new java.awt.Color(255, 204, 51));
        Pengaturan.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 12)); // NOI18N
        Pengaturan.setText("PENGATURAN");
        Pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(Pengaturan);
        Pengaturan.setBounds(270, 400, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BantuanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        //dibuat instance-nya dan diteruskan ke metode EventQueu.invokeLater yang merupakan metode statis.
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() {
                new Bantuan().setVisible(true);
            }
        });
    }//GEN-LAST:event_BantuanActionPerformed

    private void MULAIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MULAIActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Username().setVisible(true);
            }
        });
    }//GEN-LAST:event_MULAIActionPerformed

    private void HIGHSCOREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HIGHSCOREActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Highscore().setVisible(true);
            }
        });
    }//GEN-LAST:event_HIGHSCOREActionPerformed

    private void KELUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KELUARActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KELUARActionPerformed

    private void PengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengaturanActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengaturan().setVisible(true);
            }
        });
    }//GEN-LAST:event_PengaturanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuawal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuawal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bantuan;
    private javax.swing.JButton HIGHSCORE;
    private javax.swing.JButton KELUAR;
    private javax.swing.JButton MULAI;
    private javax.swing.JButton Pengaturan;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}

