/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codingan;
/**
 *
 * @author baiqm
 */
public class Score extends javax.swing.JFrame {

    /**
     * Creates new form Score
     */
    
    int skor = 0;
    public Score() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        NextScore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(757, 520));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel2.setText("SELAMAT SKOR ANDA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 60, 560, 50);

        NextScore.setBackground(new java.awt.Color(204, 102, 0));
        NextScore.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        NextScore.setText("NEXT");
        NextScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextScoreActionPerformed(evt);
            }
        });
        jPanel1.add(NextScore);
        NextScore.setBounds(580, 400, 100, 40);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 48)); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(290, 140, 180, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 750, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextScoreActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Koneksi.addscore(Username.Username.getText(), getSkor());
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuawal().setVisible(true);
            }
        });
    }//GEN-LAST:event_NextScoreActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void ambil_skor(int skor){
        this.skor = skor;
        jLabel1.setText(""+skor);
    }
    public int getSkor() {
        return skor;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
