/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codingan;
/**
 *
 * @author acer
 */
//import java.sql.*;
//import com.mysql.cj.jdbc.*;
//import javax.swing.*;
//import java.sql.DriverManager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Username extends javax.swing.JFrame {

    /**
     * Creates new form Username
//     */
    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;

        
    String namape;
    
    public Username() {
        initComponents();
        setLocationRelativeTo(null);
        Koneksi DB = new Koneksi();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernameLabel = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(757, 520));
        getContentPane().setLayout(null);

        UsernameLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        UsernameLabel.setText("USERNAME");
        getContentPane().add(UsernameLabel);
        UsernameLabel.setBounds(290, 50, 197, 63);

        Username.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        getContentPane().add(Username);
        Username.setBounds(190, 190, 370, 46);

        Next.setBackground(new java.awt.Color(204, 102, 0));
        Next.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 14)); // NOI18N
        Next.setText("NEXT");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(340, 340, 82, 36);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -120, 810, 630);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        insertDataPemain();
       
    }//GEN-LAST:event_NextActionPerformed

    public void insertDataPemain(){
        String namape = Username.getText();   
        try {
            sql = "INSERT INTO pemain (namapemain) VALUES ('"+namape+"')";
            int i = stat.executeUpdate(sql);
                if (i != 0){
                this.setVisible(false);
                new Mulai().setVisible(true);
                } else{
                JOptionPane.showMessageDialog(this,"Gagal Register");
                }
                   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
        }
    }
      
    
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Username.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Username().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Next;
    public static javax.swing.JTextField Username;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
